### ISSUE TITLE
update GEFS to handle GBBEPx version updates for gefs.v12.3.6

### ISSUE THREAD

**Issue by lipan-NOAA** [NOAA-EMC/GEFS#109]
update GEFS since GSL-prep-chem has been updated https://github.com/NOAA-GSL/GSL-prep-chem/issues/5

**Comment by XianwuXue-NOAA** [comment]
Please provide an instruction to test this update since the data is not ready in the NCO's com directory.

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA It is on prod/dcom. 
/lfs/h1/ops/prod/dcom/20230221/firewx

**Comment by XianwuXue-NOAA** [comment]
You mean the NCO has changed the dcom directory and we can test it as usual?

**Comment by lipan-NOAA** [comment]
Yes, now under the dcom both version 3 and version are available.

**Comment by XianwuXue-NOAA** [comment]
Sounds Good. Thanks.

**Comment by XianwuXue-NOAA** [comment]
@lipan-NOAA My test is located in /lfs/h2/emc/ptmp/xianwu.xue/o/gefs_v12.3.6_chem_prep_change/dev/output/20230302 on cactus. Could you please check whether the results are expected? Thanks.

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA it looks fine for me. Do you have a 06z run ?

**Comment by XianwuXue-NOAA** [comment]
No. I will setup to run 06z

**Comment by XianwuXue-NOAA** [comment]
@lipan-NOAA 06z and 12z are done! Please check the results when you have time

**Comment by lipan-NOAA** [comment]
looks fine for me

**Comment by XianwuXue-NOAA** [comment]
Thanks for your checking
