### ISSUE TITLE
link_gefs.sh requests datasets that aren't on the NOMADS server.

### ISSUE THREAD

**Issue by detached-head** [NOAA-EMC/GEFS#129]
The `link_gefs.sh` script requests the following datasets:

* `/scratch2/NCEPDEV/ensemble/noscrub/common/FIX/gefs/fix_nco_gefsv12.3`

Which isn't available on the FTP server and is therefore a blocker for running GEFS. I see someone else has raised this issue before in the `global-workflow` repository as a conversation: https://github.com/NOAA-EMC/global-workflow/discussions/1691

Would it be possible to upload this dataset to the FTP server?

Thanks in advance 😄

**Comment by detached-head** [comment]
Update: changing "NOMADS" -> "FTP".

**Comment by EricSinsky-NOAA** [comment]
Hi @detached-head, 
The GEFS fix files are not available online at this time. All the necessary fix files for GEFS will be available online in the future via the [global-workflow](https://github.com/NOAA-EMC/global-workflow).

**Comment by KateFriedman-NOAA** [comment]
Added copy of GEFSv12.3.6 fix files onto EMC ftp server temporarily for @detached-head to download. User confirmed download and I then removed the copy to free space back up on ftp server.

Will likely have a copy available publicly again down the road. Need to sort out long term data hosting plans first.

Closing as complete.
