### ISSUE TITLE
Improve and maintain GEFS_Legacy

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/GEFS#13]

**Comment by DingchenHou-NOAA** [comment]
Please double-check to make sure we have saved the last prod version of the code, and then we can close this issue.

**Comment by XianwuXue-NOAA** [comment]
No problem. I will double check today.

**Comment by XianwuXue-NOAA** [comment]
I double checked the gefs_legacy repo. tag: gefs_legacy.v10.6.0-nco includes the last prod version of GEFS_Legacy. This issue includes your changes (cleaning up unused statements and some improvement. control/gefsrun, control/setbase, parm//gefs_config and parm//gefs_config_dev after the tag: gefs_legacy.v10.6.0-nco

**Comment by DingchenHou-NOAA** [comment]
One suggestion for ISSUE-management. When a significant action (e.g PR to a branch, creation of a tag) is taken, we should add one comment here as a record for future reference.  For this this issue, the creation of the  creation of gefs_legacy.v10.6.0-nco tag is a significant step.

I suggest it is time to  close this issue as legacy has stopped in May.

**Comment by XianwuXue-NOAA** [comment]
I agree and will close it after this comment.
