### ISSUE TITLE
port GEFSv12.1.1 to WCOSS2

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/GEFS#23]

**Comment by XianwuXue-NOAA** [comment]
- [x] 1. Port the compilation of GEFS and global-workflow and its components to WCOSS2

  - [x] 1.1 Port the compilation of GEFS to WCOSS2
    - [X] 1.1.1 Based on the Acorn settings
    - [X] 1.1.2 Updated with the new environment changes for Acorn
  - [x] 1.2 Port the compilation of global-workflow to WCOSS2
    - [X] 1.2.1 Based on the Acorn settings
    - [x] 1.2.2 Updated with the new environment changes for Acorn
  - [x] 1.3 Port the compilation of fv3gfs to WCOSS2
    - [X] 1.3.1 Based on the Acorn settings
    - [x] 1.3.2 Updated with the new environment changes for Acorn 
  - [x] 1.4 Port the compilation of gsi to WCOSS2
    - [X] 1.4.1 Based on the Acorn settings
    - [x] 1.4.2 Updated with the new environment changes for Acorn
  - [x] 1.5 Port the compilation of ncep_post to WCOSS2
    - [X] 1.5.1 Based on the Acorn settings
    - [x] 1.5.2 Updated with the new environment changes for Acorn
  - [x] 1.6 Port the compilation of ufs_utils to WCOSS2
    - [X] 1.6.1 Based on the Acorn settings
    - [x] 1.6.2 Updated with the new environment changes for Acorn
  - [x] 1.7 Port the compilation of gsd_prep_chem to WCOSS2
    - [X] 1.7.1 Based on the Acorn settings
    - [x] 1.7.2 Updated with the new environment changes for Acorn
  - [x] 1.8 Port the compilation of enkf_chgres_recenter_nc to WCOSS2
    - [X] 1.8.1 Based on the Acorn settings
    - [x] 1.8.2 Updated with the new environment changes for Acorn
  - [x] 1.9 Port the compilation of gfs_bufrsnd to WCOSS2
    - [X] 1.9.1 Based on the Acorn settings
    - [x] 1.9.2 Updated with the new environment changes for Acorn

- [x] 2. Port all scripts to WCOSS2 and Test all the changes

- [x] 3. Change the structure of GEFS based on the new structural changes in WCOSS2
  - [x] 3.1 Use versions/[run.ver and build.ver]
    - [X] 3.1.1 Add build.ver and change the build_*.sh scripts
- [ ] 4. Some changes in libraries to the NCEP libraries **(NCO will not apply these changes for this WCOSS2 code transition)**
  - [ ] 4.1 w3-emc and w3-nco have been merged into a single library -- w3-emc (NCO changed their mind and will not use the merged w3-emc lib for this WCOSS2 code transition)
  - [ ] 4.2 gfsio library is no longer supported and will be removed (NCO changed their mind to keep gfsio)
      - [X] 4.2.1 ufs_utils (Removed)
      - [ ] 4.2.2 gfs_post 
  - [ ] 4.3 sfcio library is no longer supported and will be removed (NCO changed their mind to keep sfcio)
     - [X] 4.3.1 Remove it in gefs_nstgen
     - [ ] 4.3.2 ufs_utils
     - [ ] 4.3.3 gsi
     - [X] 4.3.4 fv3gfs/FV3[,NEMS] (Removed)
     - [ ] 4.3.5 gfs_post
  - [X] 4.4 nemsiogfs library is no longer supported and will be removed
     - [X] 4.4.1 ufs_utils (Removed since we don't need global_chgres)
- [ ] 5. Merge my branch into EMC branches for GEFS, G-W and its components
  - [x] 5.1 Merge FV3-GSDCHEM-WW3 into EMC repo
    - [x] 5.1.1 Merge into EMC repo
    - [x] 5.1.2 Create tag for GEFSv12.2.0
  - [x] 5.2 Merge gsi into EMC repo
    - [x] 5.2.1 Merge into EMC repo
    - [x] 5.2.2 Create tag for GEFSv12.2.0
  - [x] 5.3 ufs_utils
    - [x] 5.3.1 Merge into EMC repo
    - [x] 5.3.2 Create tag for GEFSv12.2.0
  - [x] 5.4 UPP
    - [X] 5.4.1 Merge into EMC repo
    - [x] 5.4.2 Create tag for GEFSv12.2.0
  - [x] 5.5 GSL-prep-chem
    - [x] 5.5.1 Merge into EMC repo
    - [x] 5.5.2 Create tag for GEFSv12.2.0
  - [x] 5.6 Global-Workflow
    - [x] 5.6.1 Merge into EMC repo
    - [x] 5.6.2 Create tag for GEFSv12.2.0
  - [x] 5.7 GEFS
    - [x] 5.7.1 Merge into EMC repo
    - [x] 5.7.2 Create tag for GEFSv12.2.0

**Comment by XianwuXue-NOAA** [comment]
@DingchenHou-NOAA This issue for transition GEFS & global-workflow to WCOSS2

**Comment by DingchenHou-NOAA** [comment]
You listed sun-tasks 4 days ago. Can we continue add more items to it. I mean if we can find a place to save all of such items for later reference. Comments may not be the best place for that purpose?

**Comment by XianwuXue-NOAA** [comment]
Yes. We can add more items. This is a try, we can improve it later. After that we can summarize and added to wiki or docs.
