### ISSUE TITLE
[New Function] Adding atmos_maksbn job 

### ISSUE THREAD

**Issue by DingchenHou-NOAA** [NOAA-EMC/GEFS#25]
Recently NWS SR requested for some data to be deseminated via SBN. 
Working in hotfix/addsbn branch of  DingchenHou_NOAA's fork, scripts for a new job (jgefs_atmos_addsbn) are added. 
The added scripts are based on those of jgefs_wafs of gefs v11, but with substantial re-structure.

**Comment by DingchenHou-NOAA** [comment]
Code development is done in the hotfix/addsbn branch of DingchenHou-NOAA's fork
Scripts and parm files are added for the new job jgefs_atmos_makesbn.

**Comment by DingchenHou-NOAA** [comment]
As this was not implemented, I suggest keep this issue open and the associated branch as it is, until we reach a final decision.

**Comment by XianwuXue-NOAA** [comment]
I agree. I will keep this issue.

**Comment by XianwuXue-NOAA** [comment]
Added to GEFSv12.3.1
