### ISSUE TITLE
Creating v11.3.11 tag for running SUBX with gfs.v16

### ISSUE THREAD

**Issue by DingchenHou-NOAA** [NOAA-EMC/GEFS#26]
After gfs v16 implementation (3/22/2021), SUBX (using gefs v11.3.10 to run the init jobs) needs to be updated in order to continue experimental runs. The approach is the same as in gefs_legacy.v10.6.0, adding global_chgres_nemsio uitility and change scripts related to the init (including enkf_track) jobs.

**Comment by DingchenHou-NOAA** [comment]
Work is done in the gefs.v11.3.11 branch of DingchenHou-NOAA fork
The code is from the gefs.v11.3.10 tag and modification was made to run SUBX (enkf_track and init jobs only)  as gfs v16 downstream.

**Comment by XianwuXue-NOAA** [comment]
Created tag: gefs.v11.3.11 in GEFS-EMC repo
