### ISSUE TITLE
[BugZilla] Missing debug and test target in makefile

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/GEFS#4]
This is from BugZilla system ([Item 1011](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1011)):

GEFSV12's makefiles are missing debug and test target in the makefile. 

Please check implementation standards v10.2 https://www.nco.ncep.noaa.gov/idsb/implementation_standards/Implementation%20Standards%20v10.2.pdf?:
 VI. Code Delivery and Vertical Structure, 
   A. Source Code Compilation (C or FORTRAN), 
      6. There are five critical targets that must be defined in every makefile. They are all, debug, install, clean and test. Example 13 of Appendix A contains an example of each.

**Comment by KateFriedman-NOAA** [comment]
Resolved via CMake build in merged system in global-workflow. Noting as resolved in https://docs.google.com/spreadsheets/d/1JF5GcHjqrdAIRI9nIUdxRz95GvALxHd9IDri-S3fVco/edit?gid=500564601#gid=500564601.
