### ISSUE TITLE
[BugZilla] Provide a better master build script

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/GEFS#5]
It is from BugZilla system ([Item 1010](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1010))

The master build script under GEFSV12 sorc directory does build all the codes and copy the executables to exec directory, but no clean function. Please provide a master scripts can do **build, install, and clean function** for all the source codes and also can **use it to build individual code**.

**Comment by KateFriedman-NOAA** [comment]
Made moot by merging into global-workflow and improved build script in global-workflow. Noting as resolved in https://docs.google.com/spreadsheets/d/1JF5GcHjqrdAIRI9nIUdxRz95GvALxHd9IDri-S3fVco/edit?gid=500564601#gid=500564601.
