### ISSUE TITLE
[BugZilla] firewx data directory change on WCOSS-2

### ISSUE THREAD

**Issue by lipan-NOAA** [NOAA-EMC/GEFS#65]
https://github.com/NOAA-GSL/GSL-prep-chem/issues/3

an update is needed.

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA @WalterKolczynski-NOAA 

I will submit a PR after testing.

**Comment by XianwuXue-NOAA** [comment]
Fixed in gefs.v12.3.3
