### ISSUE TITLE
Change gfs fix path to fix_nco_gfsv15

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/GEFS#8]
The GFS "fix" path is for moving forward for GFSv17 so we should change it the fix_nco_gfsv15 in both Global-workflow and GEFS repositories.

**Comment by DingchenHou-NOAA** [comment]
Is it time to close this issue?

**Comment by XianwuXue-NOAA** [comment]
Maybe later. I think we should modify the ops port2acorn version to this fix path in the next update to in case the fix path has some changes comparing with the fixing gfsv15 data

**Comment by XianwuXue-NOAA** [comment]
Have updated in GEFSv12.2.0
